### ISSUE TITLE
Launch app shortcuts in a new window

### ISSUE THREAD

**Issue by eladnava** [pbogut/Chrome-App-Shortcut-Generator#1]
Hey,
Love the generator! Well done. This is definitely a missing OSX feature.

One little problem: It opens the app URL as a new tab in a new or existing Chrome window.

Fortunately, there's a way to open the URL in its own window (and process)!

``` js
"launch": {
            "web_url": "https://web.whatsapp.com/",
            "container": "panel"
        }
```

According to the docs:

> `container`: The value "panel" makes the app appear in an app panel. By default, or when you specify "tab", the app appears in a tab.
> https://developer.chrome.com/extensions/apps

I've tested it out and it works great! What do you say? Can we add it to the generator?

**Comment by pbogut** [comment]
Hi Elad,

Glad you like it.

If you can add it as an option then feel free to make  pull request. Otherwise I can add it later this week if thats the case.

**Comment by eladnava** [comment]
@Smeagol07 Submitted a PR =)

Let me know when it goes live, can't wait to use it on my Mac!

**Comment by pbogut** [comment]
It is now live on: http://www.smeagol.pl/apps/google-app-shortcut-generator

**Comment by eladnava** [comment]
Yay, thanks! @Smeagol07
